config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :admins
  resources :statuses
  resources :profiles
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
require 'csv'

class Profile < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :birthplace, presence: true
  validates :birthdate, presence: true
  validates :gender, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :major, presence: true
  validates :graduation_year, presence: true
  validates :user_id, uniqueness: true

  def self.to_csv
    profiles = all
    CSV.generate do |csv|
      csv << column_names
      profiles.each do |profile|
        csv << profile.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/status.rb
require 'csv'

class Status < ApplicationRecord
  belongs_to :user

  def self.to_csv
    statuses = all
    CSV.generate do |csv|
      csv << column_names
      statuses.each do |status|
        csv << status.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  has_many :statuses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.profile
        redirect_to statuses_url
      else
        redirect_to new_profile_url
      end
    end

    unless user_signed_in? or admin_signed_in?
      redirect_to new_user_session_url
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    if admin_signed_in?
      @profiles = Profile.all
      respond_to do |format|
        format.html
        format.csv { send_data Profile.to_csv, filename: "profiles-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
      end
    elsif user_signed_in?
      redirect_to new_profile_url
    end
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    if admin_signed_in?
      @statuses = Status.where(user_id: @profile.user_id)
    elsif user_signed_in?
      if @profile.user_id != current_user.id
        # If their own profile exists, redirect to it
        if @profile = Profile.find_by(user_id: current_user.id)
          redirect_to profile_url(@profile)
        # Redirect to new profile if it doesn't exist
        else
          redirect_to new_profile_url
        end
      end
    end
  end

  # GET /profiles/new
  def new
    if @profile = Profile.find_by(user_id: current_user.id)
      redirect_to @profile
    elsif
      @profile = Profile.new
    end
  end

  # GET /profiles/1/edit
  def edit
    if Profile.find_by(id: params[:id]).user_id != current_user.id
      redirect_to profiles_url
    end
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profiles_url, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :birthplace, :birthdate, :gender, :address, :phone_number, :major, :graduation_year, :user_id)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]

  # GET /statuses or /statuses.json
  def index
    if admin_signed_in?
      @statuses = Status.all
      respond_to do |format|
        format.html
        format.csv { send_data Status.to_csv, filename: "statuses-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
      end
    elsif user_signed_in?
      @statuses = Status.where(user_id: current_user.id)
    end
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to statuses_url, notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        if admin_signed_in?
          format.html { redirect_to profile_url(Profile.find_by(user_id: @status.user_id)), notice: "Status was successfully updated." }
        elsif user_signed_in?
          format.html { redirect_to statuses_url, notice: "Status was successfully updated." }
        end
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    @status.destroy

    respond_to do |format|
      if admin_signed_in?
        format.html { redirect_to profile_url(Profile.find_by(user_id: @status.user_id)), notice: "Status was successfully destroyed." }
      elsif user_signed_in?
        format.html { redirect_to statuses_url, notice: "Status was successfully destroyed." }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:category, :name, :position, :address, :start_date, :end_date, :comment, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/home/index.html.erb
<!-- Content Row -->
<div class="row">

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Alumni terdaftar</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= User.all.count %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-graduation-cap fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Alumni yang sudah melengkapi profil</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= Profile.all.count %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-graduation-cap fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Alumni yang sudah mengisi status</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= Status.distinct.count('user_id') %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-circle-check fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Total status terkumpul</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= Status.all.count %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-briefcase fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Content Row -->

<div class="row">

    <!-- Bar Chart -->
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Jumlah Alumni Berdasarkan Status</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <%= bar_chart Status.group(:category).count %>
            </div>
        </div>
    </div>

    <!-- Pie Chart -->
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Jumlah Alumni Terdaftar Berdasarkan Angkatan</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <%= pie_chart Profile.group(:graduation_year).count %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracer Study</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

      <!-- Sidebar -->
      <ul class="navbar-nav bg-gradient-danger sidebar sidebar-dark accordion" id="accordionSidebar">

          <!-- Sidebar - Brand -->
          <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
              <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-school"></i>
              </div>
              <div class="sidebar-brand-text mx-3">SMK MHS Batam</div>
          </a>

          <!-- Divider -->
          <hr class="sidebar-divider my-0">

          <% if admin_signed_in? %>
          <!-- Nav Item - Dashboard -->
          <li class="nav-item">
              <%= link_to '<i class="fas fa-gauge"></i><span>    Dashboard</span>'.html_safe, root_path, class: "btn nav-link" %>
          </li>
          <!-- Nav Item - Alumni -->
          <li class="nav-item">
              <%= link_to '<i class="fas fa-graduation-cap"></i><span>    Alumni</span>'.html_safe, profiles_path, class: "btn nav-link" %>
          </li>
          <% end %>

          <!-- Nav Item - Status -->
          <li class="nav-item">
              <%= link_to '<i class="fas fa-briefcase"></i><span>    Status</span>'.html_safe, statuses_path, class: "btn nav-link" %>
          </li>

          <!-- Divider -->
          <hr class="sidebar-divider my-0">

          <!-- Nav Item - Logout -->
          <li class="nav-item">
              <%= button_to '<i class="fas fa-right-from-bracket"></i><span>    Logout</span>'.html_safe, destroy_user_session_path, method: :delete, class: "btn nav-link" %>
          </li>

      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">

          <!-- Main Content -->
          <div id="content">
          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

              <!-- Topbar Navbar -->
              <ul class="navbar-nav ml-auto">

                  <% if user_signed_in? %>
                  <!-- Nav Item - User Information -->
                  <li class="nav-item">
                      <%= link_to profiles_path, class: "nav-link" do %>
                          <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                              <% if current_user.profile %>
                                  <%= current_user.profile.name %>
                              <% else %>
                                  <%= current_user.email %>
                              <% end %>
                          </span>
                          <%= image_tag("undraw_profile.svg", class: "img-profile rounded-circle") %>
                      <% end %>
                  </li>
                  <% end %>

              </ul>

          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">
              <% if notice %>
              <div class="alert alert-success" role="notice">
                  <div class="notice"><%= notice %></div>
              </div>
              <% end %>
              <% if alert %>
              <div class="alert alert-danger" role="alert">
                  <div class="alert"><%= alert %></div>
              </div>
              <% end %>
              <%= yield %>
          </div>
          <!-- /.container-fluid -->

          </div>
          <!-- End of Main Content -->

          <!-- Footer -->
          <footer class="sticky-footer bg-white">
              <div class="container my-auto">
                  <div class="copyright text-center my-auto">
                      <span>Copyright &copy; SMK MHS Batam 2022</span>
                  </div>
              </div>
          </footer>
          <!-- End of Footer -->

      </div>
      <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracer Study</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "devise", "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'devise', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gradient-danger">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Profil</h6>
    </div>
    <div class="card-body" id="<%= dom_id profile %>">
      <div class="field form-group">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Nama</label>
          <%= form.text_field :name, class: "form-control form-control-user" %>
        </div>
      </div>
      <div class="field form-group">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Tempat lahir</label>
          <%= form.text_field :birthplace, class: "form-control form-control-user" %>
        </div>
      </div>
      <div class="field form-group">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Tanggal lahir</label>
          <%= form.date_field :birthdate, class: "form-control form-control-user" %>
        </div>
      </div>
      <div class="field form-group">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Jenis kelamin</label>
          <div><%= form.select :gender, [["Laki-laki", "Laki-laki"], ["Perempuan", "Perempuan"]] %></div>
        </div>
      </div>
      <div class="field form-group">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Alamat</label>
          <%= form.text_field :address, class: "form-control form-control-user" %>
        </div>
      </div>
      <div class="field form-group">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Nomor telepon</label>
          <%= form.text_field :phone_number, class: "form-control form-control-user" %>
        </div>
      </div>
      <div class="field form-group">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Jurusan</label>
          <%= form.text_field :major, class: "form-control form-control-user" %>
        </div>
      </div>
      <div class="field form-group">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Tahun kelulusan</label>
          <%= form.text_field :graduation_year, class: "form-control form-control-user" %>
        </div>
      </div>
    </div>
  </div>

  <div>
    <%= form.text_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Profil</h6>
  </div>
  <div class="card-body" id="<%= dom_id profile %>">
    <div class="field form-group">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <label>Nama</label>
        <input type="text" class="form-control form-control-user" placeholder="<%= profile.name %>" disabled>
      </div>
    </div>
    <div class="field form-group">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <label>Tempat lahir</label>
        <input type="text" class="form-control form-control-user" placeholder="<%= profile.birthplace %>" disabled>
      </div>
    </div>
    <div class="field form-group">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <label>Tanggal lahir</label>
        <input type="text" class="form-control form-control-user" placeholder="<%= profile.birthdate %>" disabled>
      </div>
    </div>
    <div class="field form-group">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <label>Jenis kelamin</label>
        <input type="text" class="form-control form-control-user" placeholder="<%= profile.gender %>" disabled>
      </div>
    </div>
    <div class="field form-group">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <label>Alamat</label>
        <input type="text" class="form-control form-control-user" placeholder="<%= profile.address %>" disabled>
      </div>
    </div>
    <div class="field form-group">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <label>Nomor telepon</label>
        <input type="text" class="form-control form-control-user" placeholder="<%= profile.phone_number %>" disabled>
      </div>
    </div>
    <div class="field form-group">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <label>Jurusan</label>
        <input type="text" class="form-control form-control-user" placeholder="<%= profile.major %>" disabled>
      </div>
    </div>
    <div class="field form-group">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <label>Tahun kelulusan</label>
        <input type="text" class="form-control form-control-user" placeholder="<%= profile.graduation_year %>" disabled>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to "Edit", edit_profile_path(profile), class: "btn btn-warning" %>
<% end %>

app/views/profiles/_profile_row.html.erb
<tr id="<%= dom_id profile %>">
  <td><%= profile.name %></td>
  <td><%= profile.birthplace %></td>
  <td><%= profile.birthdate %></td>
  <td><%= profile.gender %></td>
  <td><%= profile.address %></td>
  <td><%= profile.phone_number %></td>
  <td><%= profile.major %></td>
  <td><%= profile.graduation_year %></td>
  <td><%= link_to "Tampilkan", profile, class: "btn btn-info" %></td>
</tr>

app/views/profiles/edit.html.erb
<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Batalkan", profiles_path, class: "btn btn-warning" %>
</div>

app/views/profiles/index.html.erb
<% if admin_signed_in? %>

  <div id="statuses">
    <div class="card shadow mb-4">
      <div class="card-header py-3 d-sm-flex align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Alumni</h6>
        <%= link_to '<i class="fas fa-download fa-sm text-white-50"></i> Generate CSV</a>'.html_safe, profiles_path(format: 'csv'), class: "d-none d-sm-inline-block btn btn-sm btn-info shadow-sm" %>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
              <th>Nama</th>
              <th>Tempat lahir</th>
              <th>Tanggal lahir</th>
              <th>Jenis kelamin</th>
              <th>Alamat</th>
              <th>Nomor telepon</th>
              <th>Jurusan</th>
              <th>Tahun</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
              <% @profiles.each do |profile| %>
                <%= render partial: "profile_row", locals: {profile: profile} %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/new.html.erb
<%= render "form", profile: @profile %>

app/views/profiles/show.html.erb
<%= render @profile %>

<% if admin_signed_in? %>
  <% if @statuses %>
    <div id="statuses">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Status</h6>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
              <tr>
                <th>Kategori</th>
                <th>Nama</th>
                <th>Posisi</th>
                <th>Alamat</th>
                <th>Tanggal mulai</th>
                <th>Tanggal selesai</th>
                <th>Komentar</th>
                <th></th>
                <th></th>
              </tr>
              </thead>
              <tbody>
                <% @statuses.each do |status| %>
                  <%= render partial: "statuses/status", locals: {status: status} %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/statuses/_status.html.erb
<tr id="<%= dom_id status %>">
  <td><%= status.category %></td>
  <td><%= status.name %></td>
  <td><%= status.position %></td>
  <td><%= status.address %></td>
  <td><%= status.start_date %></td>
  <td><%= status.end_date %></td>
  <td><%= status.comment %></td>
  <td><%= link_to "Edit", edit_status_path(status), class: "btn btn-warning" %></td>
  <td><%= button_to "Hapus", status, method: :delete, class: "btn btn-danger" %></td>
</tr>

app/views/statuses/edit.html.erb
<%= render "form", status: @status %>

<br>

<div>
  <%= link_to "Batalkan", statuses_path, class: "btn btn-warning" %>
</div>

app/views/statuses/index.html.erb
<div id="statuses">
  <div class="card shadow mb-4">
    <div class="card-header py-3 d-sm-flex align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Status</h6>
      <% if admin_signed_in? %>
        <%= link_to '<i class="fas fa-download fa-sm text-white-50"></i> Generate CSV</a>'.html_safe, statuses_path(format: 'csv'), class: "d-none d-sm-inline-block btn btn-sm btn-info shadow-sm" %>
      <% end %>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
          <tr>
            <th>Kategori</th>
            <th>Nama</th>
            <th>Posisi</th>
            <th>Alamat</th>
            <th>Tanggal mulai</th>
            <th>Tanggal selesai</th>
            <th>Komentar</th>
            <th></th>
            <th></th>
          </tr>
          </thead>
          <tbody>
            <% @statuses.each do |status| %>
              <%= render status %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to "Tambahkan status", new_status_path, class: "btn btn-primary" %>
<% end %>

app/views/statuses/new.html.erb
<%= render "form", status: @status %>

<br>

<div>
  <%= link_to "Batalkan", statuses_path, class: "btn btn-warning" %>
</div>

app/views/statuses/show.html.erb
<%= render @status %>

<div>
  <%= link_to "Edit this status", edit_status_path(@status) %> |
  <%= link_to "Back to statuses", statuses_path %>

  <%= button_to "Destroy this status", @status, method: :delete %>
</div>